// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCg3EHJY8mpIMNZWJsMyOgcODo5EQXYtGY',
    appId: '1:276108478793:web:e19de5746c9af5d551f298',
    messagingSenderId: '276108478793',
    projectId: 'login-aec47',
    authDomain: 'login-aec47.firebaseapp.com',
    storageBucket: 'login-aec47.firebasestorage.app',
    measurementId: 'G-L35MSV03YK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCwevyIAavxcHYtlQCMD2cq8V3LPkHDM4Y',
    appId: '1:276108478793:android:a985533fb6f9f65f51f298',
    messagingSenderId: '276108478793',
    projectId: 'login-aec47',
    storageBucket: 'login-aec47.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA_LTXqwq-XRgAcN2mYK8eiTQczRxyLjm4',
    appId: '1:276108478793:ios:e3f2590622cda1af51f298',
    messagingSenderId: '276108478793',
    projectId: 'login-aec47',
    storageBucket: 'login-aec47.firebasestorage.app',
    iosBundleId: 'com.example.projectLogin',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA_LTXqwq-XRgAcN2mYK8eiTQczRxyLjm4',
    appId: '1:276108478793:ios:e3f2590622cda1af51f298',
    messagingSenderId: '276108478793',
    projectId: 'login-aec47',
    storageBucket: 'login-aec47.firebasestorage.app',
    iosBundleId: 'com.example.projectLogin',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCg3EHJY8mpIMNZWJsMyOgcODo5EQXYtGY',
    appId: '1:276108478793:web:7639ca2e1ae94b2151f298',
    messagingSenderId: '276108478793',
    projectId: 'login-aec47',
    authDomain: 'login-aec47.firebaseapp.com',
    storageBucket: 'login-aec47.firebasestorage.app',
    measurementId: 'G-F8CTSZ0FFV',
  );
}
